name: Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == '/refs/heads/main'
    steps:
    - uses: actions/checkout@master
    - name: Package
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* README.md CHANGELOG.md '
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
